### ISSUE TITLE
Triggering Lockout?

### ISSUE THREAD

**Issue by kyuuketsukikurai** [FriendsOfGalaxy/galaxy-integration-steam#52]
I hope you guys can help me.
I've been using the plugin for a while now, but lately, it's been triggering the incorrect password lockout, and I can't figure out why. It shows as Offline (Retry), but then if I go to login on Steam itself, it gives me the lockout error. 
Waiting a half hour lets it all connect, but I'd like to fix the cause, if I could.
The logs show a bunch of error 5 entries, before the 84. I figured out that 84 is the temp block error.

I couldn't attach them, and they're too big for pastebin. I've trimmed the log to when I reopened Galaxy this morning, but I have the full log, if needed.

[edit-plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4535447/edit-plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Hey @kyuuketsukikurai 

this shouldn't happen, i will prepare a fix for the next version of the plugin that won't try retrying on token error 5 since it seems like that retry won't work on a short timespan anyway.

Thanks for the report.

**Comment by kyuuketsukikurai** [comment]
Thanks for the response.
What's the Error 5 mean, if you don't mind me asking?

**Comment by rautobias** [comment]
As I understand it, Steam does not accept the stored login token. The reason is not yet known.
Related Issue: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/39#issuecomment-614089248

**Comment by FriendsOfGalaxy** [comment]
Literally error 5 means Invalid Password
`InvalidPassword = 5`
but receiving it doesnt make any sense during authenticating with token  because we dont even provide any password. 

Even more so because during my testing it worked out that after a while (hour or 2) retrying the authentication with that same token is successful. It seems that steam can send an incorrect error at some times and right now i'm investigating why (maybe the specific server with which we are trying to connect is overloaded so we should try a different one)

**Comment by kyuuketsukikurai** [comment]
Yes, logging in after the lockout ended usually works. 
It does look like it's giving this error before the Wrong Password one. 
2020-04-26 13:45:44,099 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "3", "error": {"code": 4, "message": "Backend error"}}

I don't usually work in Python, but I do work in bug investigation in software. Let me know, if there's anything you need on environment or actual data being sent.

**Comment by FriendsOfGalaxy** [comment]
I've created a test version which should never cache the server list and extend it with subsequent retries (also it shouldnt ever go as far as locking the account from too many retries ) If you could please see if it works for you. @kyuuketsukikurai  @rautobias 

[steam_server_choosing_test.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4540228/steam_server_choosing_test.zip)

**Comment by FriendsOfGalaxy** [comment]
I've created a test version which should never cache the server list and extend it with subsequent retries (also it shouldnt ever go as far as locking the account from too many retries ) If you could please see if it works for you. @kyuuketsukikurai  @rautobias 

[steam_server_choosing_list_extend.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4540262/steam_server_choosing_list_extend.zip)


to use it 
1 Close Galaxy Client
2 Go to your 
C:\Users\username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8 folder
3 Delete all its contents
4 Unpack the provided zip file in that folder
5 Run galaxy
 if everything went well plugin version shown in logs will be 0.50.3

**Comment by kyuuketsukikurai** [comment]
Updated successfully. Would you like the log?

**Comment by rautobias** [comment]
Error 84 seems to be fixed with your provided version. But unfortunately error 5 (as in #39) is still reproducible.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4541842/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
@kyuuketsukikurai  if possible, yes please, does the new version not lock you out anymore?

@rautobias  it seems that thats not the case of error 5 then,

got another clue about possible time desynchronization between user and server (https://github.com/seishun/node-steam/issues/236#issuecomment-230512770), will investigate futher and let you know, in the meantime i will probably release the change so 84 doesn't happen again.

**Comment by FriendsOfGalaxy** [comment]
@kyuuketsukikurai  @rautobias  i've released version 0.50.3 to the public which should fix the issue of locking out (not the error 5 yet, still working on that) its a bit different than the one provided in this task so please disregard that one (you can delete your plugin and let the new one download, it will automatically through galaxy client)

**Comment by kyuuketsukikurai** [comment]
Mine seems much better, and I haven't had the issue since updating to 0.50.3.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4564234/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by kyuuketsukikurai** [comment]
Just noticed your last message. I'll remove the plugin and install the release.

**Comment by kyuuketsukikurai** [comment]
Still getting issues with Error 5. Gets stuck on connecting, then drops to Offline.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4570899/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by pierrebai** [comment]
Tokens can expire. It's not necessarily merely a question of trying later.

**Comment by FriendsOfGalaxy** [comment]
@pierrebai  this is not an issue of expiring token since using the same token couple of hours later will work.

**Comment by LazyTarget** [comment]
Hi, I have had this issue for a while now. And now I wanted to get to the bottom of it 😄 So now I tried it on my laptop and get the same issue..

I am running the latest version, which is 0.51.2 now

Attaching todays log:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4827515/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

![Steam: Offline. Retry...](https://user-images.githubusercontent.com/959409/85619296-5d80e500-b662-11ea-9fbf-02415b4e411c.png)

**Comment by LazyTarget** [comment]
A follow up question:
If you where to click disconnect, to then try to connect again.
Would I lose any data? Like games, achievements or playtime?

**Comment by kyuuketsukikurai** [comment]
@LazyTarget I'm not a dev myself, but disconnecting has been the only fix that works for me. I've not had any issues at all with lost data. All the information you mentioned is pulled from Steam when you connect (and when you sync integrations), as far as I know.

**Comment by kyuuketsukikurai** [comment]
@FriendsOfGalaxy Has there been any progress with the "Offline (Retry)" issue? 
Is there anything I can help with?

**Comment by pizza2code** [comment]
My Steam account is also being locked out temporarily, occurred just today.  

How do I determine the plugin version?  Tried searching the Program Files folder, but I only see the official plugins.

**Comment by codykonior** [comment]
My Steam also locked today from this plugin.

**Comment by kyuuketsukikurai** [comment]
The easiest way is probably by checking the logs.
They're located in:
%programdata%\GOG.com\Galaxy\logs

**Comment by FriendsOfGalaxy** [comment]
Hi, I'm closing as this should not happen any more, but feel free to mention/reopen if still occurs
